### ISSUE TITLE
Protocol "" is unknown - s5max

### ISSUE THREAD

**Issue by Ibot1001** [ccoors/Valeronoi#10]
Hi, 
I'm trying to get your project working, but while connecting, I get an "unknown Protocol error". See Images;

![stats](https://user-images.githubusercontent.com/73443259/111614896-6f05b080-87e0-11eb-9db5-7bee2eea6328.PNG)

![error](https://user-images.githubusercontent.com/73443259/111614900-6f9e4700-87e0-11eb-9013-e144457d7145.PNG)

**Comment by ccoors** [comment]
See Issue #8 
Add `http://` before the address. The next release will do this automatically.

**Comment by Ibot1001** [comment]
Thank you, works now :)
