### ISSUE TITLE
M1 Support works fine

### ISSUE THREAD

**Issue by Dodoooh** [ccoors/Valeronoi#15]
it's not an issue but I thought I'd share a quick note anyway

So you can change the passage "should work" to "works fine" ;) 
Just tested it on a M1 Macbook Pro. It works fine. 👍

Thanks for your good work.

**Comment by ccoors** [comment]
Thanks for confirming! :+1: Fixed in b239f2e43a0c871c5ca47d907260a21a21d7116b
