### ISSUE TITLE
Support for Valetudo 2022.02

### ISSUE THREAD

**Issue by Hypfer** [ccoors/Valeronoi#22]
https://github.com/Hypfer/Valetudo/commit/bbdf2ec1f21287e4b0397508a608880028c20b29 slightly changes the API

Now, the REST endpoint returns a ValetudoWifiStatus object so this check will fail

https://github.com/ccoors/Valeronoi/blob/064451de4fd29d0ba895d9162b2c6ac7787f8717/src/robot/robot.cpp#L82-L91

**Comment by ccoors** [comment]
b3b88a1a5fdbbf57e948482519568ae46617f274
