### ISSUE TITLE
Support for Roborock Gen1?

### ISSUE THREAD

**Issue by Seafo** [ccoors/Valeronoi#8]
Roborock Gen1 does not have persistent map support. Is that a requirement for Valeronoi?  Room cleaning works fine in Valetudo  as long as you do segment cleaning so Wifi mapping should also be possible, right? See attached errors in Valeronoi-0.1.2-Windows-portable-x86_64. Great idea and project btw!

![image](https://user-images.githubusercontent.com/47945490/111475613-918ac180-872d-11eb-86e5-f8fc7328a9dd.png)
![image](https://user-images.githubusercontent.com/47945490/111475648-9a7b9300-872d-11eb-9f4c-37e44fd694cc.png)

**Comment by ccoors** [comment]
Yes, it does work with Gen 1. You can use it without a persisted map if you do segment/zone cleaning. Valeronoi has no method of starting those though, so you'll have to start recording and then switch to Valetudo itself to start the segment cleaning there.

The second error looks weird, when did you get that one?

**Comment by Seafo** [comment]
The second error appear after pressing "Connect" button. Is there any way to generate a log file?
![image](https://user-images.githubusercontent.com/47945490/111478537-74a3bd80-8730-11eb-9e88-9ecef8b69112.png)

**Comment by ccoors** [comment]
Weird. And the "Test connection" button is working with exactly that configuration? Can you show a screenshot of the Robot Setup Dialog?

Sorry, haven't figured out how to view the Log on Windows. It should be on stdout, but I have no idea how to get it on Windows. I will add a log file in a later version.

**Comment by Seafo** [comment]
The HTTP authentication is not enabled in Valetudo.
![image](https://user-images.githubusercontent.com/47945490/111480319-27285000-8732-11eb-9216-225a857028fe.png)

**Comment by ccoors** [comment]
The address has to start with `http://`. Weird that the connection test still works. I'll investigate that later.

**Comment by Seafo** [comment]
That did it! I can confirm that it works with http:// before the internal ip. Thanks!
I leave the issue open since you maybe want to add a error msg or adjust so the program add http if needed.

**Comment by ccoors** [comment]
Fixed in 2657e47d08e3dcff554acc852639e64f772a3a0f
