### ISSUE TITLE
Support for Valetudo RE

### ISSUE THREAD

**Issue by mukhametshin** [ccoors/Valeronoi#9]
It would be very kind if the [Valetudo RE](https://github.com/rand256/valetudo) could be also supported one day.
Currently I got the following error after having Test Connection button pressed:

![image](https://user-images.githubusercontent.com/4593167/111484612-37422e80-8736-11eb-8aa1-4f27a74ffa4e.png)

**Comment by ccoors** [comment]
Sorry, this is out of scope for this project. I would not even accept a ready-to-merge pull request. I do not want to encourage the usage of Valetudo RE in any way, shape or form. There will be no further discussion.

**Comment by mukhametshin** [comment]
@ccoors thank you for your response! No problem, sure, your project your rules ;)

**Comment by bruvv** [comment]
@ccoors may I ask what you reasons are for not encouraging the use of RE?

**Comment by ccoors** [comment]
Apart from my personal feelings for RE, which I won't go into (there has been enough talk about that on various channels), adding support for RE would require a lot of work since the old API works quite differently.

**Comment by tefracky** [comment]
> Sorry, this is out of scope for this project. I would not even accept a ready-to-merge pull request. I do not want to encourage the usage of Valetudo RE in any way, shape or form. There will be no further discussion.



> Apart from my personal feelings for RE, which I won't go into (there has been enough talk about that on various channels), adding support for RE would require a lot of work since the old API works quite differently.

This really sound like "I don't want, becaus I don't want." Well, thats bad, so the only hope is that someome will fork it.
